algorandfoundation/ARCs

- ARCs/arc-0003.md
This Pull Request is meant to subsumes https://github.com/algorandfoundation/ARCs/pull/6 following the comments received.
The support for {id} substitution is added to allow later support
for storing asset metadata on chain like proposed in
https://github.com/algorandfoundation/ARCs/pull/6#issuecomment-882511661
> ARC-0003: Clarify URI rules and support for {id}

- ARCs/arc-0003.md
Since the community is split on the exact definition of NFTs, this PR proposes
to use a definition that leaves open the possibility to name "NFTs" ASAs that
are not strictly speaking NFTs (or pure NFT).
> ARC-0003: Rename NFT to Pure NFT and Clarify Text

- ARCs/arc-0003.md
Previous version did not allow to store data that a smart contract could
access. This PR adds the option to hash extra metadata in the asset
metadata ASA parameter.
> ARC-0003 Support for Extra Metadata

- ARCs/arc-0003.md
Currently, there is no easy way to check the integrity of files
pointed by the metadata JSON. In particular, when buying an
NFT, the seller may then change for example the image of the
NFT without the buyer having anyway to prove that the image
actually changed.
This PR proposes to fix this issue by adding additional integrity
properties.
> ARC-0003: Support for Integrity Properties

- ARCs/arc-0003.md
This PR is meant to try to provide clearer guidelines
so that clients such as marketplaces can more easily
display NFTs, following some discussions in
#3
Concretely:
1. It adds the fields `external_url`, `animation_url` and
`background_color` used on OpenSea.
2. It clarifies the use of those fields in the example of
a song.
3. It adds `_mimetype` fields that are optional
(for compatiblity with OpenSea) but highly recommended
4. It switched to the term `fields` for JSON fields
to avoid confusion with properties/attributes of the
asset.
Rationale:
1. Keep the fields in the "root" of the JSON metadata
file (as opposed to the properties) limited to
what is required for preview in a markeplace/gallery.
In particular `image` and `animation_url` can be,
for some assets, just preview, as opposed …
> ARC-0003: Adding MIME types and OpenSea fields

- ARCs/arc-0003.md
As mentioned by @barnjamin in https://github.com/algorandfoundation/ARCs/issues/3#issuecomment-913177134, support for relative URI seems necessary to allow storing the JSON Metadata file together with the files it refers to in the same IPFS directory.
> ARC-0003: Support for relative URI

- ARCs/arc-0004.md
Creating a PR for easier comments before merging.
> ARC-4: ABI

- ARCs/arc-0001.md
- ARCs/arc-0005.md
- ARCs/arc-0006.md
- ARCs/arc-0007.md
- ARCs/arc-0008.md
- ARCs/arc-0009.md
- ARCs/arc-0010.md
- ARCs/arc-0011.md
From #8
with the following changes:
* use of `genesisID`/`genesisHash` instead of `network` for `enable`
* enforce main networks' hashes from genesisID
* allow `enable` to return no account for just access to blockchain
* support of list of group of transactions in posting
* clarify error handling in many cases
* add security considerations in many places
* add optional `signTxns` and `postTxns` to wallet standard
* clarify requirements for confirmation when posting transactions
* use `BaseHTTPClient` from algorand/js-algorand-sdk#477
for `getAlgodv2Client` and `getIndexerClient`
* other minor changes
Include #29  and #28 
Main points to discuss:
* splitting the error standards out of ARC-0001 and make it a living standard
* allow optional argument to post without waiting for confirmation …
> Adding ARCs 0004 to 0011 and updating ARC 0001

- ARCs/arc-0005.md
- ARCs/arc-0006.md
- ARCs/arc-0007.md
- ARCs/arc-0008.md
- ARCs/arc-0009.md
- ARCs/arc-0010.md
- ARCs/arc-0011.md
I've also written a small runnable demo which demonstrates an implementation of all of the API functionality specified by this group of ARCs. [except for `window.algorand`, since it is a cli demo]
https://github.com/reach-sh/algo-demo-wallet
> Reach wallet arcs (0005 thru 0011)

- ARCs/arc-0001.md
Following comment
https://github.com/algorandfoundation/ARCs/issues/1#issuecomment-895374290
from @DanBurton
This PR is to be dicussed.
`signTxns` is indeed more logical.
`signTxn` can still exist and be mapped to `signTxns` for backward
compatibility.
So I don't think this should create too many issues
but please raise your voice if it does.
> ARC-0001: Renaming signTxn to signTxns

- ARCs/arc-0004.md
Changes:
* minor style changes, in particular using **MUST**…
* allow descriptions `desc` in interfaces and contracts
* add comment that interfaces designer should be mindful to prevent collisions of method selectors between interfaces that are likely to be implemented together by the same application.
* clarify that method names do not need to be uniq
* restrict contract and interface names to Interface to  `[_A-Za-z][A-Za-z0-9_]*` , which would be useful if later we want to say that contract XXX implements interface YYY. Allowing full UTF-8 or spaces can quickly make things cumbersome.
* make interface names `ARC-XXXX...` reserved for ARCs
* allow method selector for `_optIn` and `_closeOut` to not be unique
* add a note that reference types can be part of a tuple is in the 15-th …
> ARC-0004: Misc changes

- ARCs/arc-0004.md
In order to simplify and make more consistent how contract creation and OnCompletion actions work, this PR removes the special methods `_optIn` and `_closeOut`. In their place, I've explicitly defined "bare application calls" and provided guidance for how and when they should be supported.
The general idea is that if your app creation call or OnCompletion action requires no arguments and no return value, then your contract **SHOULD** implement these operations as bare application calls. Otherwise, if there are some situations in which you require arguments or a return value, your contract **SHOULD NOT** allow bare application calls for this case, and instead provide one or more ABI methods which can be called with the appropriate action.
Additionally, in order to make it easier to read …
> ARC-0004: Change how contract creation and OnCompletion actions work

- ARCs/arc-0016.md
Establishes a standard for how to declare an NFT's traits inside a token's metadata.
> ARC for standardizing traits (attributes) in token metadata

- ARCs/arc-0004.md
Change ABI to last call.
Handling
https://github.com/algorandfoundation/ARCs/pull/55#discussion_r768239652:
Reduced terminology to "Application", "Contract", "Interface". No more
"smart contracts" to indicate Algorand Applications.
Change "future revisions" to "future ABI-related ARC" as if we follow
Ethereum EIP, only ARC-0 should be living and have revisions.
One question after this pass:
Why prefixing the return log value?
Is the caller supposed to check the prefix?
> ARC-0004 Minor clarifications and last call

- ARCs/arc-0004.md
Saw some typos while reading it.
For the commas -> semicolons, my prettier plugin was complaining about it so I also committed the change.
> ARC-0004: fix typos

- ARCs/arc-0005.md
- ARCs/arc-0006.md
- ARCs/arc-0007.md
Some references to other arc files returned a 404 on GitHub due to incorrect capitalization of arc filenames.
> Fix incorrect capitalization for arc filename refs

- ARCs/arc-0004.md
With this change it will be possible to create flexible ABI-compliant interfaces without resolving to dirty hacks.
Example use-cases in which this change is handy:
- `optin(asset[])void`
- `distributerewards((account,uint64)[])void` - or any batch operation
In my opinion, such methods are useful and are likely to be used by application creators. Their current incompatibility with the ABI will result in non-standardized approaches being taken.
> ARC-4: Remove constraints on reference types

- ARCs/arc-0001.md
this way dApps don't have to have special cases for single transactions and can always send a group to the wallet.
> Update arc-0001.md to support transaction groups with only 1 transaction

- ARCs/arc-0007.md
this way dApps don't have to have special cases for single transactions and can always send a group to the wallet.
> Update arc-0007.md to support transaction groups with only 1 transaction

- ARCs/arc-0001.md
- ARCs/arc-0002.md
- ARCs/arc-0003.md
- ARCs/arc-0004.md
- ARCs/arc-0005.md
- ARCs/arc-0006.md
- ARCs/arc-0007.md
- ARCs/arc-0008.md
- ARCs/arc-0009.md
- ARCs/arc-0010.md
- ARCs/arc-0011.md
- ARCs/arc-0019.md
Attaching discussion links to ARCs by adding the `discussions-to` attribute to the header of each ARC.
This will allow presenting those links in the github page.
> Attach discussions

- ARCs/arc-0019.md
ARC19 should realistically be considered final at this point as almost 14K ARC19 NFTs have already been minted - all completely immutable.  
Any changes to the URL spec of ARC19 at this point will likely need to be an independent ARC.
> Moving ARC19 status to Final.

- ARCs/arc-0004.md
The encoding for `k`, which specifies the length of a variable length array was not specified. Talking to @barnjamin this value should be encoded as uint16. This PR specifies that.
> ARC-0004: Specify encoding for variable array length

- ARCs/arc-0004.md
An upcoming release of Algorand allows Applications to create and manage `Boxes`, a named set of bytes owned by the Application that created it.
In order to read or write to a box, it _MUST_ be specified in the ApplicationCallTransaction much like the current requirement for Assets/Apps/Accounts.
This PR introduces boxes as a reference type to be encoded in the same way as other reference types.
> ARC4 - adding boxes

- ARCs/arc-0008.md
I propose to add a recommendation inside the security consideration for dApps using the `signAndPostTxns` function to avoid potential issues (eg: Multiple submissions of transactions).
> Arc-0008 Update of security consideration for dApps (Waiting Screen)

- ARCs/arc-0009.md
This fixes the links to the base http client & some spelling mistakes.
> nit(arc-9): fix links & spelling

- ARCs/arc-0006.md
* `EnablNetworkOpts` -> `EnableNetworkOpts`: missing e
* TypeScript definitions were not actually valid, interface declaration shouldn't have =
> fix(arc-6): TS definitions are not valid TS

- ARCs/arc-0076.md
This standard specifies a computation for seed bytes for H999 account. For general adoption it is better for people to remember passphrase than mnemonic. With this standard person can hash the passphrase and receive the seed bytes for X25529 algorand account.
> ARC-0076 - Password Account

- ARCs/arc-0032.md
- assets/arc-0032/application.schema.json
- assets/arc-0032/contract.schema.json
This PR Updates ARC-0032 to describe the current as-is usage of ARC-32 being used in Beaker and various algokit-utils libraries. The current specification is not perfect, but felt it is important to have the ARC updated to reflect it more accurately as a starting point
> Update ARC-32: Update to match current implementation used by Beaker and algokit-utils

- pages/wallets.md
This adds the ARC support  matrix for Exodus. I'm not sure of the NFT ARCs, will update those in follow up once I know more.
@SudoWeezy
> feat: add exodus support matrix

- ARCs/arc-0055.md
- ARCs/arc-onchain-multisig-management.md
This is an initial draft for the on-chain multisignature application proposal. (If someone can think of a good name for this, please share)
The TL;DR is it's a smart contract design you and your friends can use to help with signing multisig transactions.
The smart contract itself does not perform any multsignature operations, but rather it facilitates the distribution of the unsigned transactions between the multisignature constituents, and allowing them to store their signature on-chain.
This should make using multisig accounts and signing transactions much faster and simpler.
> ARC-55 On-Chain Msig Apps

- ARCs/arc-0054.md
Added a deployments section to ARC-54 containing the app IDs of the contracts deployed to each network.
> Add ARC-54 App IDs

- ARCs/arc-0054.md
Both @SilentRhetoric and myself agree that this was an error in the ARC. Total supply should *not* remove the burned supply. This metric is captured via `Available` supply. 
Also added in addresses to the deployments.
> Fix error in ARC54 total (and add addresses)

- ARCs/arc-0000.md
We already had these 2 headers:
• superseded-by (only if Status is Deprecated): “To be used to refer to the newer ARC(s) that replace the older ARC.”
• replaces: “To be used to refer to an earlier ARC that is replaced by this ARC.”
The following are proposed to be added:
• extended-by: “To be used to refer to the newer ARC(s) that add functionality to the existing, still active ARC.”
• extends: “To be used as a reference from a new ARC that cannot be used independently.”
> ARC-0 Add Tracking mechanism for extension

- ARCs/arc-0071.md
This is the new iteration of ARC-0071 PR using a new approach more fit the requirements of SouldBound tokens.
> ARC-0071 Consensual Soul Bound ASA [New Approach]

- ARCs/arc-0071.md
Fixed the mistaken sentence and corrected to `The Freeze parameter **MUST** be set to the Issuer Address` for the Issued state of SBTs.
> Arc 71- Fixed a text mistake

- ARCs/arc-0059.md
Fixed the name of the claim method in the explanation of claiming an asset
> Fix typo in ARC-59

- ARCs/arc-0059.md
Adds the ARC56 JSON and deployed app IDs to ARC59. Spec and functionality remain unchanged
> Add deployments and ARC56 JSON to ARC59
