algorandfoundation/ARCs

ARCs/arc-0001.md

ARC-0001: Add support for a message per group

---

ARCs/arc-0003.md

In particular avoid duplicate schema with and without localization:
thanks @scholtz - https://forum.algorand.org/t/arc-0003-algorand-standard-asset-parameters-conventions-for-fungible-and-non-fungible-tokens/4133/2\?u\=fabrice

ARC-0003: Cleaning and slight restructuring

---

ARCs/arc-0001.md

+ minor fixes
algorandfoundation/ARCs#1

ARC-0001: Allow to restrict nb of txns signed

---

ARCs/arc-0003.md

* Replacing tabs with whitespaces
* Clarifying that all fields are optional
* Marking ARC-0003 as last call

ARC-0003 Last Call

---

ARCs/arc-0001.md

Adding stxn field following comment
https://github.com/algorandfoundation/ARCs/issues/1#issuecomment-895374290
from @DanBurton

ARC-0001: Support for stxn field

---

ARCs/arc-0069.md

This PR adds the popular [ARC69](https://github.com/algokittens/arc69) metadata spec to the `algorandfoundation/ARCs` GitHub repository
This ARC helps NFTs load as quickly and reliably as possible, with attributes, [backwards compatibility for existing NFTs](https://github.com/algokittens/arc69/blob/master/pre-existing-NFTs.md), and updateability (upgrading stats in an RPG, fixing typos, etc.)
The Algo NFT community has enthusiastically adopted this ARC, with more series adding metadata every day! Here are just a few of the awesome series using this ARC:
- Yieldlings
- M.N.G.O
- Eclectic Flamingos
- Banana Mints
- Stupid Horses
This ARC works great in production, on popular platforms like [NFT Explorer](https://www.nftexplorer.app/asset/359181888), …

New ARC: ARC-0069: Community Algorand Standard Asset Parameters Conventions for Digital Media Tokens

---

ARCs/arc-draft_asa_url_templating.md

ARC-0019: NFT ASA URL templating proposal for mutable IPFS CID replacement in URLs.

---

ARCs/arc-0004.md

Fixes minor typos I encountered when reviewing ARC-4.

ARC-4:  Fix typos

---

README.md

Link the github page in the README file

Link the github page in the README file

---

README.md
_config.yml
index.html

moved the ARCs tables to the index page, removed links in the header and updated README

Change pages layout

---

ARCs/arc-0016.md
ARCs/arc-0025.md
ARCs/arc-0069.md

added missing links to discussions

Linking discussions

---

ARCs/arc-0018.md

Draft of Royalty Enforcement Specification using freeze/clawback roles to perform the transfer.
Example implementation: https://github.com/algorand-devrel/royalty

ARC-0018 ASA Transfer Royalty Enforcement Specification

---

ARCs/arc-0022.md

Extend arc-4 to add `read-only` annotation to methods

Create arc 22

---

ARCs/arc-0001.md

Fixes various typos and grammar issues

fix: ARC-0001 typos

---

ARCs/arc-0001.md

fix: ARC-0001 typo

---

ARCs/arc-0004.md

Reverts algorandfoundation/ARCs#123

Revert "ARC4 - adding boxes"

---

ARCs/arc-0028.md

It is the update of the original PR https://github.com/algorandfoundation/ARCs/pull/113 based on every relevant comment.

ARC-0028 : Events 

---

ARCs/arc-0072.md

This is the NFT standard from #162 separated from interface detection.

add NFT standard draft arc-72

---

ARCs/arc-0073.md

This is the interface detection standard from #162 separated out into its own PR.

add interface detection draft arc-73

---

ARCs/arc-0033.md

I open this PR for any clarification needed on the process.
Feel free to comment.

ARC - 33 xGov clarification

---

ARCs/arc-0059.md

Added additional authors to ARC59 in alphabetical order

updated authors
